DROP DATABASE IF EXISTS AIRLINE;
CREATE DATABASE AIRLINE;
USE AIRLINE;

CREATE TABLE FLIGHTS (FLIGHT_NO NUMERIC (5) NOT NULL,
	DEPARTURE VARCHAR(30),
	ARRIVAL VARCHAR(30),
	FLIGHT_TYPE VARCHAR (15),
	SEATS NUMERIC (3),
	FREE_SEATS NUMERIC (3),
    PRIMARY KEY (FLIGHT_NO));
 
 CREATE TABLE CUSTOMERS (CUSTOMERS_NAME VARCHAR (20),
    CUSTOMERS_LAST_NAME VARCHAR (20),
    CUSTOMERS_ID NUMERIC (5) NOT NULL,
    CITIZENSHIP VARCHAR (45),
    BIRTHDATE DATE);

CREATE TABLE RESERVATIONS (RESERVATIONS_NO NUMERIC (5) NOT NULL,
	CUSTOMERS_ID NUMERIC (5) NOT NULL,
	CLIENT_CODE NUMERIC (5) NOT NULL,
	FLIGHT_NO NUMERIC(5) NOT NULL,
	COST NUMERIC (5) NOT NULL);
    
ALTER TABLE CUSTOMERS
ADD CONSTRAINT CUSTOMERS_ID_PK PRIMARY KEY(CUSTOMERS_ID);

ALTER TABLE RESERVATIONS
ADD CONSTRAINT RES_ID_PK PRIMARY KEY(RESERVATIONS_NO),
ADD CONSTRAINT CUSTOMERS_ID_FK FOREIGN KEY (CUSTOMERS_ID) REFERENCES CUSTOMERS(CUSTOMERS_ID),
ADD CONSTRAINT FLIGHT_NO_FK FOREIGN KEY (FLIGHT_NO) REFERENCES FLIGHTS (FLIGHT_NO);

INSERT INTO FLIGHTS VALUES 
(1,'ATHENS','MOSCOW','ABROAD',100,32),
(2,'SKG','CHANIA','HOME',70,15),
(3,'SKG','PARIS','ABROAD',200,21),
(4,'ATHENS','LONDON','ABROAD',230,0),
(5,'ATHENS','CHIOS','HOME',100,5);

INSERT INTO CUSTOMERS VALUES 
('NIKOS','KOUKOS',15,'GREEK','1969-09-06'),
('KONSTANTINOS','PAPADOPOULOS',23,'GREEK','1983-07-12'),
('VINCENT','CASSEL',34,'FRENCH','1966-11-23'),
('BENEDICT','CUMBERBATCH',42,'BRITISH','1976-07-19'),
('YIANNIS','OIKONOMIDIS',37,'GREEK','1967-03-12');

INSERT INTO RESERVATIONS VALUES 
(25,15,35,1,70),
(78,23,49,2,25),
(179,34,46,3,130),
(69,42,78,4,200),
(89,37,26,5,65);

SELECT * FROM FLIGHTS;

SELECT * FROM CUSTOMERS;

SELECT * FROM RESERVATIONS;

SELECT FLIGHT_NO, COUNT(*) AS RESERVATIONS
FROM RESERVATIONS
GROUP BY FLIGHT_NO;

SELECT CUSTOMERS_NAME, CUSTOMERS_LAST_NAME, SUM(COST) AS TOTAL_COST
FROM CUSTOMERS
INNER JOIN RESERVATIONS
ON CUSTOMERS.CUSTOMERS_ID = RESERVATIONS.CUSTOMERS_ID
GROUP BY CUSTOMERS_NAME, CUSTOMERS_LAST_NAME
ORDER BY TOTAL_COST DESC;

CREATE VIEW FLIGHTS_VIEW AS
SELECT FLIGHT_NO, DEPARTURE, ARRIVAL, FLIGHT_TYPE, SEATS, FREE_SEATS
FROM FLIGHTS;

CREATE VIEW RESERVATIONS_VIEW AS
SELECT RESERVATIONS_NO, CUSTOMERS_ID, CLIENT_CODE, FLIGHT_NO, COST
FROM RESERVATIONS;

CREATE OR REPLACE VIEW FLIGHTS_UPDATABLE AS
SELECT FLIGHT_NO, DEPARTURE, ARRIVAL, FLIGHT_TYPE, SEATS, FREE_SEATS
FROM FLIGHTS
WHERE FREE_SEATS > 0;

CREATE OR REPLACE VIEW RESERVATIONS_INSERTABLE AS
SELECT CUSTOMERS_ID, CLIENT_CODE, FLIGHT_NO, COST
FROM RESERVATIONS;
